# Generated by Django 3.1.4 on 2021-06-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
