# Generated by Django 3.2.3 on 2021-06-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210607_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
