# Generated by Django 3.1.4 on 2021-06-07 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210607_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 20, 31, 38, 150564)),
        ),
    ]
