# Generated by Django 3.1.4 on 2021-06-07 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210607_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateField(default=datetime.datetime(2021, 6, 22, 21, 2, 7, 418751)),
        ),
    ]
