# Generated by Django 3.1.4 on 2021-06-07 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210607_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateField(default=datetime.date(2021, 6, 22)),
        ),
    ]
