# Generated by Django 3.1.4 on 2021-06-07 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(default=datetime.date(2021, 6, 23)),
        ),
    ]
